packages:
  - 'packages/*'
  - 'apps/*'
  - 'services/*'
  - 'tests/*'
  - 'plugins/*'
  - 'integrations/turbopack-ariada'
  - 'integrations/gulp-ariada'
  - 'integrations/grunt-ariada'
  - 'integrations/parcel-ariada'
