packages:
  - "tools/*"
  - "packages/*"
  - "apps/*"
  - "services/*"
  - "tests/*"
  - "plugins/*"
  - "integrations/turbopack-ariada"
  - "integrations/vercel-ariada"
  - "integrations/wordpress-ariada"
  - "integrations/axure-ariada"
  - "integrations/azure-swa-ariada"
  - "integrations/backstage-ariada"
  - "integrations/balsamiq-ariada"
  - "integrations/discord-ariada"
  - "integrations/framer-ariada"
  - "integrations/jsr-ariada"
  - "integrations/jupyterlab-ariada"
  - "integrations/lunacy-ariada"
  - "integrations/marvel-ariada"
  - "integrations/nextra-ariada"
  - "integrations/penpot-ariada"
  - "integrations/protopie-ariada"
  - "integrations/raycast-ariada"
  - "integrations/slack-ariada"
  - "integrations/statuspage-ariada"
  - "integrations/teams-ariada"
  - "integrations/uxpin-ariada"
  - "integrations/vitepress-ariada"
  - "integrations/vuepress-ariada"
  - "integrations/web-ide-ariada"
  - "integrations/whimsical-ariada"
  - "integrations/zeplin-ariada"
  - "integrations/gulp-ariada"
  - "integrations/grunt-ariada"
  - "integrations/parcel-ariada"
